#!/usr/bin/perl
#
use strict;
$|=1;

my $source = "/var/www/cpan/modules.conf";
my $log = "/var/www/cpan/cpan_install.log";

(-e $log) and unlink($log);


if(-e $source)
{
  (-T $source) or die "'$source' is not a text file\n";
  open(FH, "$source") or die "Cannot open '$source' for reading\n";
  while(<FH>)
  {
    /^\s*#/ and next;
    s/[^\w:\-]//g;
    /^\-/ and die "Attempt to pass flag to cpanm via module name '$_'\n";
    while(/\.\./) { s/\.\.//g; }
    /[\w+]/ or next;
    logme("Installing ( if required ) $_");
    my $cmd = `export PERL_CPANM_HOME='/var/www/cpan/'; cpanm $_ --local-lib /var/www/cpan/perl5/ --self-contained --verbose >> $log 2>&1`;
  }
  close(FH);
}


sub logme
{
  my $arg = shift;
  open(LOG, ">> $log");
  print "[".localtime()."] $arg\n";
  close(LOG);
}
